// popular treds
export const START_GET_POPULAR_TREDS = 'START_GET_POPULAR_TREDS'
export const SUCCESS_GET_POPULAR_TREDS = 'SUCCESS_GET_POPULAR_TREDS'
export const ERROR_GET_POPULAR_TREDS = 'ERROR_GET_POPULAR_TREDS'

// tred
export const START_GET_TRED = 'START_GET_TRED'
export const SUCCESS_GET_TRED = 'SUCCESS_GET_TRED'
export const ERROR_GET_TRED = 'ERROR_GET_TRED'

// comments
export const START_ADD_COMMENT = 'START_ADD_COMMENT'
export const SUCCESS_ADD_COMMENT = 'SUCCESS_ADD_COMMENT'
export const ERROR_ADD_COMMENT = 'ERROR_ADD_COMMENT'

export const START_GET_COMMENTS = 'START_GET_COMMENTS'
export const SUCCESS_GET_COMMENT = 'SUCCESS_GET_COMMENT'
export const ERROR_GET_COMMENTS = 'ERROR_GET_COMMENTS'

export const CLOSE_COMMENTS = 'CLOSE_COMMENTS'
