export const START_GET_POPULAR_TREDS = 'START_GET_POPULAR_TREDS'
export const SUCCESS_GET_POPULAR_TREDS = 'SUCCESS_GET_POPULAR_TREDS'
export const ERROR_GET_POPULAR_TREDS = 'ERROR_GET_POPULAR_TREDS'

export const START_GET_TRED = 'START_GET_TRED'
export const SUCCESS_GET_TRED = 'SUCCESS_GET_TRED'
export const ERROR_GET_TRED = 'ERROR_GET_TRED'